project_id = "ynlepnfnhyeswtiakyve"

[functions.analyze-product]
verify_jwt = false

[functions.fetch-products]
verify_jwt = false

[functions.analyze-style]
verify_jwt = true

[functions.match-products]
verify_jwt = true