// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynlepnfnhyeswtiakyve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlubGVwbmZuaHllc3d0aWFreXZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ0NjI0NDksImV4cCI6MjA1MDAzODQ0OX0.4YkzB2lwCrMIBA7Cf4IqrvTfBp3MDyWMpoQBJhtbK4I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);